import {AuditTrail} from "./audit-trail.class";

export class LedgerItemEntity extends AuditTrail {
    uid!: string; // generated by UUID
    clientId!: string;
    transactionDate!: string; // ISO Format
    transType!: string; // advance, escrow close, fee, to client, from client
    advanceId!: string; // collection ID
    advanceName!: string; // advanceName usually Address Line 1
    advanceAgreementNumber!: string;
    description!: string; // place for a PromoCode
    amount!: number; // $0.00

    constructor() {
        super();
    }
}
